### ISSUE TITLE
Example simple did not work for Python 2

### ISSUE THREAD

**Issue by mnewsha** [dbousque/lymp#8]
Hi,
Unfortunately I could not run on python 2 the example simple you have provided, for python 3 it worked fine, but unfortunately the error happened for python 2 only in function get_string with this error:
```
ocamlbuild -use-ocamlfind -pkgs lymp -tag thread simple.native && ./simple.native
Finished, 4 targets (4 cached) in 00:00:00.
Fatal error: exception Lymp.Wrong_Pytype("simple.get_message : expected str but python returned bytes")
```
maybe there is something wrong with pymongo in version 2 of python. The version of pymongo is 3.6.0

**Comment by dbousque** [comment]
Hi @mnewsha. Thanks for reporting the issue. I'm pretty sure it's in `lymp.py`, since the Exception means that OCaml received Python bytes from `lymp.py`, but we expected to receive a Python string (rightfully), so `lymp.py` somehow sent `bytes` instead of `str`. I will look into it today and let you know :)

**Comment by dbousque** [comment]
Actually, this behavior is expected : https://github.com/dbousque/lymp/blob/master/srcs/lymp.py#L68. In Python 2, returned `unicode` strings are `Pystr of string` on OCaml's side, and returned `str` strings are `Pybytes of bytes`. I will update the example to take this into account. Thanks for reporting.

**Comment by mnewsha** [comment]
OK. Thanks for information.
